version: '3.8'

services:
  prediction-api:
    build: .
    ports:
      - "8008:7860"
    volumes:
      - ./models:/app/models
      - ./app/users.db:/app/app/users.db
    env_file:
      - .env
    environment:
      - ENV=production
